### PR TITLE
enhancement/pom_plugin_update

### PR DESCRIPTION
**Pull request by losete**
Pull request made for updating pom plugins

### CODE REVIEW

**Comment by franrua** [comment]
Why the branch is merged but the PR still open?

**Comment by losete** [comment]
> Why the branch is merged but the PR still open?

I needed the information from a PR that wasn't merged

**Review by sebascm — CHANGES_REQUESTED** [review]
You must specify maven minimal version. You can check it with command mvn versions:display-plugin-updates.
You can use Maven Enforcer plugin. If you encounter problems, it can be due to the version of Maven, look at Pablo's [PR](https://github.com/PabloGalegoC/spring-boot-maven-angular-starter/pull/3)

**Comment by losete** [comment]
> You must specify maven minimal version. You can check it with command mvn versions:display-plugin-updates.
> You can use Maven Enforcer plugin. If you encounter problems, it can be due to the version of Maven, look at Pablo's [PR](https://github.com/PabloGalegoC/spring-boot-maven-angular-starter/pull/3)

Done

**Review by sebascm — APPROVED** [review]

**Review by franrua — APPROVED** [review]

**Pull request merged**
